import { useEffect, useState } from "react";
import { getPayouts, processPayout } from "../../services/financeService";

export default function DispatcherPayouts(){
 const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await getPayouts();if(r.success)setItems(r.data?.payouts||[]);else setError(r.message||"Unable to load payout requests")}catch(e){setError(e.response?.data?.message||"Unable to load payout requests")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const act=async(id,action)=>{const note=action==='reject'?window.prompt('Reason for rejection:')||'Payout rejected by dispatcher':'';try{const r=await processPayout(id,action,note);if(!r.success){alert(r.message);return}alert(r.message);load()}catch(e){alert(e.response?.data?.message||"Unable to process payout")}};
 const pending=items.filter(x=>x.status==='pending'); const approved=items.filter(x=>x.status==='approved'); const paid=items.filter(x=>x.status==='paid');
 return <section><div className="breadcrumb">Dispatcher / <strong>Payouts</strong></div><div className="page-title-row"><div><span className="eyebrow">RIDER PAYOUT DESK</span><h1>Pay riders</h1><p>Approve payout requests and mark them paid after the bank transfer is completed.</p></div><button className="ghost-btn" onClick={load}>↻ Refresh</button></div>{error&&<div className="alert error">{error}</div>}<div className="stat-grid four"><div className="stat-card"><span>Pending</span><strong>{pending.length}</strong><small>Needs review</small></div><div className="stat-card"><span>Approved</span><strong>{approved.length}</strong><small>Ready to pay</small></div><div className="stat-card"><span>Paid</span><strong>{paid.length}</strong><small>Completed</small></div><div className="stat-card"><span>Queue value</span><strong>₦{items.filter(x=>['pending','approved'].includes(x.status)).reduce((a,x)=>a+Number(x.amount||0),0).toLocaleString()}</strong><small>Pending + approved</small></div></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">PAYOUT QUEUE</span><h2>Rider payout requests</h2></div></div>{loading?<div className="loading-state"><div className="loader-ring"/><span>Loading payout requests…</span></div>:items.length===0?<div className="empty-state"><div className="empty-icon">₦</div><h3>No payout requests</h3><p>Rider requests will appear here after an approved rider requests a payout.</p></div>:<div className="table-wrap"><table><thead><tr><th>Rider</th><th>Amount</th><th>Bank</th><th>Account</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><strong>{p.rider_name}</strong><br/><small>{p.rider_phone}</small></td><td><strong>₦{Number(p.amount).toLocaleString()}</strong></td><td>{p.bank_name||'—'}</td><td>{p.account_name||'—'}<br/>•••• {p.account_number_last4||'----'}</td><td><span className={`status ${p.status==='paid'?'green':p.status==='rejected'?'red':p.status==='approved'?'blue':'orange'}`}>{p.status}</span></td><td>{p.status==='pending'?<div className="action-buttons"><button className="approve-btn" onClick={()=>act(p.id,'approve')}>Approve</button><button className="text-btn danger-text" onClick={()=>act(p.id,'reject')}>Reject</button></div>:p.status==='approved'?<div className="action-buttons"><button className="approve-btn" onClick={()=>act(p.id,'paid')}>Mark paid</button><button className="text-btn danger-text" onClick={()=>act(p.id,'reject')}>Reject</button></div>:<span>Monitor</span>}</td></tr>)}</tbody></table></div>}</div></section>
}
