import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { loginUser } from "../../services/authService";
import { useAuth } from "../../context/AuthContext";

export default function Login(){
 const navigate=useNavigate(); const {login}=useAuth(); const [form,setForm]=useState({email:"",password:""}); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 const submit=async e=>{e.preventDefault();setLoading(true);setMessage("");try{const result=await loginUser(form);if(result.success){login(result.data);const role=result.data.user.role;navigate(`/${role}`);}else setMessage(result.message);}catch(err){console.error(err);setMessage("Unable to connect to the GOFAST server.");}finally{setLoading(false)}};
 return <div className="auth-page"><div className="auth-brand"><span className="brand-logo">G</span><span><strong>GOFAST</strong><small>Dispatch & Logistics</small></span></div><div className="auth-split"><div className="auth-story"><span className="eyebrow">SMARTER DELIVERY</span><h1>Every package.<br/><em>One clear journey.</em></h1><p>Manage deliveries, riders and customers from one fast, reliable operations platform.</p><div className="story-stats"><div><strong>24/7</strong><span>delivery visibility</span></div><div><strong>4</strong><span>role workspaces</span></div><div><strong>1</strong><span>control center</span></div></div><div className="route-preview"><span>Yola</span><i/><span>Jimeta</span><b>GOFAST LIVE ROUTE</b></div></div><div className="auth-card"><div className="auth-card-head"><span className="eyebrow">WELCOME BACK</span><h2>Sign in to GOFAST</h2><p>Access your delivery workspace.</p></div>{message&&<div className="alert error">{message}</div>}<form onSubmit={submit}><label>Email address<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@company.com" required/></label><label>Password<div className="password-field"><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Enter your password" required/><span>●●●</span></div></label><div className="form-meta"><label className="check"><input type="checkbox"/> Remember me</label><button type="button" className="link-btn" onClick={()=>setMessage("Password reset will be connected to the notification service.")}>Forgot password?</button></div><button className="primary-btn wide" disabled={loading}>{loading?<><span className="button-spinner"/> Signing in...</>:"Sign in →"}</button></form><div className="auth-footer">New to GOFAST? <Link to="/register">Create an account</Link></div></div></div></div>
}
