import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { registerCustomer, registerRider } from "../../services/authService";

const initial = { full_name:"", email:"", phone:"", password:"", nin:"", bvn:"", vehicle_type:"Motorcycle", vehicle_number:"", bank_name:"", account_name:"", account_number:"" };

export default function Register(){
  const nav=useNavigate(); const [role,setRole]=useState("customer"); const [form,setForm]=useState(initial); const [msg,setMsg]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [verificationUrl,setVerificationUrl]=useState("");
  const change=e=>setForm({...form,[e.target.name]:e.target.value});
  const submit=async e=>{e.preventDefault();setLoading(true);setError("");setMsg("");setVerificationUrl("");try{const r=role==='rider'?await registerRider(form):await registerCustomer(form);if(r.success){setMsg(r.message);setVerificationUrl(r.data?.verification_url||"");}else setError(r.message||"Registration failed")}catch(e){setError(e.response?.data?.message||"Unable to connect to the GOFAST server.")}finally{setLoading(false)}};
  return <div className="auth-page register-page"><div className="auth-brand"><span className="brand-logo">G</span><span><strong>GOFAST</strong><small>Dispatch & Logistics</small></span></div><div className="register-wrap"><div className="register-card"><div className="auth-card-head"><span className="eyebrow">GET STARTED</span><h2>Create your GOFAST account</h2><p>Customers book deliveries. Riders join the fleet after identity verification.</p></div>
    <div className="role-switch"><button className={role==='customer'?'active':''} onClick={()=>setRole('customer')} type="button">Customer</button><button className={role==='rider'?'active':''} onClick={()=>setRole('rider')} type="button">Rider</button></div>
    {msg&&<div className="alert success">{msg}{verificationUrl&&<><br/><a href={verificationUrl} target="_blank" rel="noreferrer">Open verification link</a></>}</div>}{error&&<div className="alert error">{error}</div>}
    <form onSubmit={submit}><div className="form-two"><label>Full name<input name="full_name" value={form.full_name} onChange={change} placeholder="Your full name" required/></label><label>Phone number<input name="phone" value={form.phone} onChange={change} placeholder="080..." required/></label></div><label>Email address<input type="email" name="email" value={form.email} onChange={change} placeholder="you@example.com" required/></label><label>Password<input type="password" name="password" minLength="8" value={form.password} onChange={change} placeholder="At least 8 characters" required/></label>
    {role==='rider'&&<div className="rider-register-block"><div className="form-section"><h3>Identity verification</h3><p className="muted-copy">Your NIN and BVN are encrypted in the backend and only the last four digits are shown to administrators.</p><div className="form-two"><label>NIN<input name="nin" inputMode="numeric" maxLength="11" value={form.nin} onChange={change} placeholder="11 digits" required/></label><label>BVN <span className="optional-label">(optional)</span><input name="bvn" inputMode="numeric" maxLength="11" value={form.bvn} onChange={change} placeholder="11 digits"/></label></div></div><div className="form-section"><h3>Vehicle details</h3><div className="form-two"><label>Vehicle type<select name="vehicle_type" value={form.vehicle_type} onChange={change}><option>Motorcycle</option><option>Tricycle</option><option>Car</option><option>Van</option></select></label><label>Vehicle number<input name="vehicle_number" value={form.vehicle_number} onChange={change} placeholder="Plate / registration" required/></label></div></div><div className="form-section"><h3>Payout account</h3><p className="muted-copy">This account receives dispatcher-approved rider payouts.</p><div className="form-two"><label>Bank name<input name="bank_name" value={form.bank_name} onChange={change} placeholder="Bank name" required/></label><label>Account name<input name="account_name" value={form.account_name} onChange={change} placeholder="Account holder" required/></label></div><label>Account number<input name="account_number" inputMode="numeric" maxLength="10" value={form.account_number} onChange={change} placeholder="10 digits" required/></label></div></div>}
    <button className="primary-btn wide" disabled={loading}>{loading?"Creating account...":role==='rider'?"Submit rider application →":"Create customer account →"}</button></form><div className="auth-footer">Already have an account? <Link to="/login">Sign in</Link></div></div><div className="register-side"><span className="eyebrow">TRUSTED DELIVERY OPERATIONS</span><h2>{role==='rider'?'Join the GOFAST rider network.':'Book, pay and track with confidence.'}</h2><p>{role==='rider'?'Rider applications are checked before delivery access and payouts are enabled.':'Customers verify their email, pay securely and follow every delivery.'}</p><div className="feature-line"><b>✓</b><span><strong>Email verification</strong><small>Protect every account before access.</small></span></div><div className="feature-line"><b>✓</b><span><strong>{role==='rider'?'NIN + BVN verification':'Secure online payment'}</strong><small>{role==='rider'?'Identity and payout details stay protected.':'Pay delivery charges through Paystack.'}</small></span></div><div className="feature-line"><b>✓</b><span><strong>{role==='rider'?'Dispatcher payouts':'Live delivery tracking'}</strong><small>{role==='rider'?'Request earnings when your balance is available.':'Follow orders from pickup to delivery.'}</small></span></div></div></div></div>
}
