import { useNavigate } from "react-router-dom";

const data={
  "Customer management":{eyebrow:"CUSTOMER OPERATIONS",cards:[["Active customers","1,284","+12.4%"],["New this month","186","+8.1%"],["Verified accounts","96%","Healthy"]],items:[["Aisha Bello","aisha@example.com","Active"],["Kashim Medicals","kashim@example.com","Active"],["Northern Bites","northern@example.com","Active"]],action:"Add customer"},
  "Staff & permissions":{eyebrow:"PEOPLE & ACCESS",cards:[["Dispatchers","18","3 online"],["Pending access","3","Review now"],["Active staff","16","Healthy"]],items:[["Operations Desk","dispatcher@gofast.local","Dispatcher"],["Branch Supervisor","supervisor@gofast.local","Supervisor"],["Finance Desk","finance@gofast.local","Finance"]],action:"Create staff account"},
  "Branches":{eyebrow:"NETWORK CONTROL",cards:[["Active branches","3","Growing"],["Orders today","1,284","+18.2%"],["Fleet coverage","91%","On target"]],items:[["Yola","742 orders","93.4% success"],["Gombe","318 orders","90.1% success"],["Jalingo","224 orders","88.7% success"]],action:"Add branch"},
  "Reports & analytics":{eyebrow:"BUSINESS INTELLIGENCE",cards:[["Revenue","₦8.42m","+11.8%"],["Delivery success","91.0%","+2.4%"],["Avg. delivery","48 min","-6 min"]],items:[["Weekly operations","Orders, revenue and success","Ready"],["Rider performance","Completion and earnings","Ready"],["Payment report","Paystack and cash activity","Ready"]],action:"Export report"},
  "System settings":{eyebrow:"PLATFORM CONTROL",cards:[["API status","Online","Healthy"],["Payment gateway","Paystack","Connected"],["Notifications","Enabled","24/7"]],items:[["Business profile","GOFAST identity and branches","Configure"],["Payment settings","Gateway and settlement","Configure"],["Security","Sessions, access and audit logs","Configure"]],action:"Save settings"},
  "Account settings":{eyebrow:"ACCOUNT SECURITY",cards:[["Password","Protected","Healthy"],["Sessions","1 active","This device"],["Notifications","Enabled","On"]],items:[["Password & security","Keep your account protected","Manage"],["Notification preferences","Choose important alerts","Manage"],["Sign-in activity","Review recent sessions","Review"]],action:"Update settings"},
  "Profile":{eyebrow:"YOUR PROFILE",cards:[["Role","Workspace user","Active"],["Account","Verified","Secure"],["Status","Active","Online"]],items:[["Personal information","Name, phone and email","Edit"],["Workspace access","Role and permissions","View"],["Security","Password and sessions","Manage"]],action:"Edit profile"},
  "Notifications":{eyebrow:"ALERT CENTER",cards:[["Unread","2","New"],["Operational","1","Today"],["Account","1","Today"]],items:[["Workspace ready","Your GOFAST workspace is ready.","New"],["Delivery operations","No critical delivery alerts.","Today"],["Security","Your account is protected.","Today"]],action:"Mark all read"},
  "Support":{eyebrow:"GOFAST SUPPORT",cards:[["Response time","< 15 min","Average"],["Open tickets","0","All clear"],["Availability","24/7","Online"]],items:[["Delivery issue","Report a delayed, failed or damaged delivery","Open ticket"],["Payment issue","Get help with a payment or payout","Open ticket"],["Account issue","Password, verification or access support","Open ticket"]],action:"Contact support"},
  "Incident log":{eyebrow:"OPERATIONS SAFETY",cards:[["Open incidents","1","Needs review"],["Resolved today","8","+2"],["SLA risk","0","Clear"]],items:[["GF-10462","Package damage reported","Open"],["GF-10444","Recipient unavailable","Resolved"],["GF-10431","Late pickup","Resolved"]],action:"Log incident"},
  "Activity log":{eyebrow:"AUDIT TRAIL",cards:[["Events today","428","+18%"],["Dispatcher actions","184","Tracked"],["System events","244","Tracked"]],items:[["Order GF-10491","Rider assigned","2 min ago"],["Rider verification","Application reviewed","14 min ago"],["Payout request","Dispatcher action pending","32 min ago"]],action:"Refresh activity"},
};

export default function WorkspacePage({role="GOFAST",title,description}){
 const navigate=useNavigate(); const d=data[title]||{eyebrow:"GOFAST WORKSPACE",cards:[["Status","Online","Healthy"],["Tasks","Ready","Today"],["Visibility","100%","Live"]],items:[["Workspace module","Connected to GOFAST operations","Ready"],["Live data","API and database integration","Connected"],["Next action","Use the controls on this page","Ready"]],action:"Refresh"};
 return <section className="workspace-module"><div className="breadcrumb">GOFAST / <strong>{title}</strong></div><div className="page-title-row"><div><span className="eyebrow">{d.eyebrow}</span><h1>{title}</h1><p>{description}</p></div><button className="primary-btn" onClick={()=>alert(`${d.action} action is ready to connect to live data.`)}>{d.action} →</button></div><div className="module-stats">{d.cards.map(([a,b,c])=><div className="module-stat" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className="module-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">LIVE VIEW</span><h2>Everything you need</h2></div><button className="text-btn" onClick={()=>window.location.reload()}>Refresh ↻</button></div><div className="module-list">{d.items.map(([a,b,c],i)=><button className="module-row" key={a} onClick={()=>alert(`${a}: ${b}`)}><span className="module-row-icon">{i+1}</span><span><strong>{a}</strong><small>{b}</small></span><b>{c}</b><em>→</em></button>)}</div></div><div className="panel module-side"><span className="eyebrow">GOFAST CONTROL</span><h2>Built for action</h2><p>Every workspace is structured around the tasks that matter most, with clear status, quick actions and responsive controls.</p><button className="secondary-btn" onClick={()=>navigate(-1)}>← Back</button><div className="module-check"><span>✓</span> Responsive on mobile</div><div className="module-check"><span>✓</span> Role-based access</div><div className="module-check"><span>✓</span> Connected to operations</div></div></div></section>;
}
