import { useEffect, useState } from "react";
import { getPayouts, processPayout } from "../../services/financeService";
const money = v => `₦${Number(v || 0).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export default function DispatcherPayouts(){
  const [data,setData]=useState({payouts:[],stats:{}}); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const load=async()=>{setLoading(true);try{const r=await getPayouts();if(r.success)setData(r.data);else setError(r.message)}catch(e){setError(e.response?.data?.message||"Unable to load payout queue.")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const act=async(id,action)=>{setMessage("");setError("");const prompt=action==='paid'?"Confirm that you have completed the bank transfer to this rider?":action==='reject'?"Reject this payout request?":"Approve this payout request?";if(!window.confirm(prompt))return;try{const r=await processPayout(id,action);if(!r.success)throw new Error(r.message);setMessage(r.message);load()}catch(e){setError(e.response?.data?.message||e.message||"Unable to process payout.")}};
  const stats=data.stats||{};
  return <section><div className="breadcrumb">Dispatcher / <strong>Rider payouts</strong></div><div className="page-title-row"><div><span className="eyebrow">FINANCE OPERATIONS</span><h1>Rider payouts</h1><p>Review requests, approve them, and mark bank transfers as paid.</p></div><button className="ghost-btn" onClick={load}>↻ Refresh</button></div>
    {message&&<div className="alert">✓ {message}</div>}{error&&<div className="alert danger-alert">{error}</div>}
    <div className="stat-grid four"><div className="stat-card"><span>Total requests</span><strong>{stats.total||0}</strong><small>All time</small></div><div className="stat-card"><span>Pending amount</span><strong>{money(stats.pending_amount)}</strong><small>Needs action</small></div><div className="stat-card"><span>Paid amount</span><strong>{money(stats.paid_amount)}</strong><small>Completed</small></div><div className="stat-card"><span>Queue</span><strong>{data.payouts?.filter(p=>p.status==='pending').length||0}</strong><small>Waiting for review</small></div></div>
    <div className="panel"><div className="panel-head"><div><span className="eyebrow">PAYOUT QUEUE</span><h2>Requests from riders</h2></div></div>{loading?<p>Loading payout queue...</p>:<div className="table-wrap"><table><thead><tr><th>Rider</th><th>Amount</th><th>Bank</th><th>Account</th><th>Status</th><th>Requested</th><th>Action</th></tr></thead><tbody>{data.payouts?.length?data.payouts.map(p=><tr key={p.id}><td><strong>{p.rider_name}</strong><br/><small>{p.rider_phone}</small></td><td><strong>{money(p.amount)}</strong></td><td>{p.bank_name||"—"}</td><td>{p.account_name||"—"}<br/>•••• {p.account_number_last4||"----"}</td><td><span className={`status ${p.status==='paid'?'green':p.status==='rejected'?'red':p.status==='approved'?'blue':'orange'}`}>{p.status}</span></td><td>{new Date(p.requested_at).toLocaleString()}</td><td>{p.status==='pending'?<div className="action-row"><button className="text-btn" onClick={()=>act(p.id,'approve')}>Approve</button><button className="text-btn" onClick={()=>act(p.id,'paid')}>Mark paid</button><button className="text-btn danger-text" onClick={()=>act(p.id,'reject')}>Reject</button></div>:p.status==='approved'?<button className="primary-btn small-btn" onClick={()=>act(p.id,'paid')}>Mark paid</button>:<span className="muted-copy">Completed</span>}</td></tr>):<tr><td colSpan="7"><div className="empty-state"><strong>No payout requests</strong><small>New rider requests will appear here.</small></div></td></tr>}</tbody></table></div>}</div>
  </section>
}
