import { useEffect,useState } from "react";
import { getRiderApplications,reviewRider } from "../../services/managementService";

export default function AdminRiders(){
 const [riders,setRiders]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await getRiderApplications();if(r.success)setRiders(r.data?.riders||[]);else setError(r.message||"Unable to load rider applications.")}catch(e){setError(e.response?.data?.message||"Unable to load rider applications. Check that the verification database migration has been imported.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const review=async(id,status)=>{const reason=status==='rejected'?window.prompt('Reason for rejection:')||'Application did not meet verification requirements':'';try{const r=await reviewRider(id,status,reason);window.alert(r.message);if(r.success)load()}catch(e){window.alert(e.response?.data?.message||"Unable to update rider verification.")}};
 const pending=riders.filter(r=>r.verification_status==='pending').length;
 return <section><div className="breadcrumb">Administration / <strong>Rider verification</strong></div><div className="page-title-row"><div><span className="eyebrow">KYC & FLEET CONTROL</span><h1>Rider verification</h1><p>Review identity, vehicle and payout details before riders enter the delivery fleet.</p></div><button className="ghost-btn" onClick={load}>↻ Refresh applications</button></div><div className="stat-grid four"><div className="stat-card"><span>Pending review</span><strong>{pending}</strong><small>Needs your approval</small></div><div className="stat-card"><span>Total riders</span><strong>{riders.length}</strong><small>Applications</small></div><div className="stat-card"><span>Approved</span><strong>{riders.filter(r=>r.verification_status==='approved').length}</strong><small>Fleet ready</small></div><div className="stat-card"><span>Rejected</span><strong>{riders.filter(r=>r.verification_status==='rejected').length}</strong><small>Needs changes</small></div></div>{error&&<div className="alert error">{error}</div>}<div className="panel"><div className="panel-head"><div><span className="eyebrow">APPLICATION QUEUE</span><h2>{pending?`${pending} rider${pending===1?'':'s'} waiting for review`:'Rider applications'}</h2></div></div>{loading?<div className="loading-state"><div className="loader-ring"/><span>Loading rider applications…</span></div>:riders.length===0?<div className="empty-state"><div className="empty-icon">🚚</div><h3>No rider applications yet</h3><p>New rider registrations will appear here automatically after they submit their verification details.</p></div>:<div className="table-wrap"><table><thead><tr><th>Rider</th><th>Identity</th><th>Vehicle</th><th>Payout account</th><th>Status</th><th>Decision</th></tr></thead><tbody>{riders.map(r=><tr key={r.id}><td><strong>{r.full_name}</strong><br/><small>{r.email} · {r.phone}</small></td><td>NIN •••• {r.nin_last4||'—'}<br/>BVN •••• {r.bvn_last4||'—'}</td><td>{r.vehicle_type||'—'}<br/><small>{r.vehicle_number||'—'}</small></td><td>{r.bank_name||'—'}<br/><small>{r.account_name||'—'} · •••• {r.account_number_last4||'—'}</small></td><td><span className={`status ${r.verification_status==='approved'?'green':r.verification_status==='rejected'||r.verification_status==='suspended'?'red':'orange'}`}>{r.verification_status}</span></td><td>{r.verification_status==='pending'?<div className="action-buttons"><button className="approve-btn" onClick={()=>review(r.id,'approved')}>✓ Approve</button><button className="reject-btn" onClick={()=>review(r.id,'rejected')}>Reject</button></div>:<button className="text-btn" onClick={()=>review(r.id,'suspended')}>Suspend rider</button>}</td></tr>)}</tbody></table></div>}</div></section>
}
